config/routes.rb
Rails.application.routes.draw do
  resources :job_packages
  resources :package_vehicle_models
  resources :packages
  root                       'users#static'
  resources :reviews,         only: [:create]
  resources :locations,       only: [:index]
  resources :vehicles,        only: [:create] 
  resources :bookings,        only: [:create]    
  resources :manufacturers,   only: [:index]
  resources :users,           only: [:create] 
  resources :vendors,         only: [:create] 
  resources :offers,          only: [:index]
  resources :jobs,            only: [:index]  
  # resources :getoffers
  # resources :notifications
  # resources :prices
  # resources :jobs
  #resources :vehicle_models, only: [:show,:index]  
  #resources :vehicles, only: [:index]
  resources :dealerships, only: [:index] 
  post   'allreviews'               => 'dealerships#all_reviews' 
  post   'vehiclebookings'          => 'vehicles#vehicle_bookings' 
  post   'getdealers'               => 'vehicles#get_dealers'  
  post   'allvehicles'              => 'manufacturers#all_vehicles'
  post   'uservehicles'             => 'users#user_vehicles'
  post   'userbookings'             => 'users#user_bookings'
  post   'usersend'                 => 'users#send_otp'
  post   'userresend'               => 'users#resend'
  post   'userupdate'               => 'users#update'   
  post   'mobile'                   => 'password_resets#create'
  post   'resetpassword'            => 'password_resets#update'
  post   'verifyresend'             => 'password_resets#resend'
  post   'signup'                   => 'users#create'
  post   'verify'                   => 'otps#create'
  post   'resend'                   => 'otps#update'
  post   'signin'                   => 'sessions#create'
  post   'signout'                  => 'sessions#destroy'
  post   'vehicleupdate'            => 'vehicles#update'
  post   'vehicleremove'            => 'vehicles#destroy' 
# post   'bookingupdate'            => 'bookings#update'
# post   'bookingremove'            => 'bookings#destroy'
  post   'facebook'                 => 'sessions#facebook'
  post   'google'                   => 'sessions#google'
  post   'oauthmobile'              => 'sessions#oauth_mobile'
  post   'delete'                   => 'users#destroy'
  post   'meraotp'                  => 'users#mera_otp'
  post   'dealerbookings'           => 'vendors#booking'
  post   'vendorsignup'             => 'vendors#create'   
  post   'vendorsignin'             => 'vendors#signin'  
  post   'vendorsignout'            => 'vendors#signout'
  post   'checkoffer'               => 'offers#check_offer'
  post   'usernotifications'        => 'users#user_notifications'
  post   'vendordealerships'        => 'vendors#dealerships'
  post   'vendordealership'         => 'vendors#dealership' 
  post   'vendorbookings'           => 'vendors#bookings'
  post   'vendorbooking'            => 'vendors#booking' 
  post   'droptime'                 => 'vendors#set_droptime' 
  post   'assignpickupdriver'       => 'vendors#assign_pickup_driver'
  post   'assigndropdriver'         => 'vendors#assign_drop_driver'
  post   'updatebooking'            => 'vendors#update_booking'
  post   'dealershipdrivers'        => 'vendors#drivers'
  post   'availabledrivers'         => 'vendors#available_drivers'
  post   'unavailabledrivers'       => 'vendors#unavailable_drivers'  
  post   'subvendorsignup'          => 'dealership_employee#create_sub_vendor'
  post   'removesubvendor'          => 'dealership_employee#remove_sub_vendor' 
  post   'serviceadvisorsignup'     => 'dealership_employee#create_service_advisor'
  post   'removesadvisor'           => 'dealership_employee#remove_service_advisor'
  post   'driversignup'             => 'dealership_employee#create_driver'
  post   'driversignin'             => 'drivers#signin'
  post   'removedriver'             => 'dealership_employee#remove_driver' 
  post   'dealershipuserbookings'   => 'vendors#user_bookings'
  post   'driverstatus'             => 'vendors#driver_status'
  post   'vendordriverbookings'     => 'vendors#driver_bookings'
  get    'bookingstatuses'          => 'bookings#booking_statuses'
  post   'vendormakeoffer'          => 'vendors#make_offer'
  post   'vendormanufacturers'      => 'vendors#vendor_manufacturers'
  post   'getdriverbookings'        => 'drivers#bookings'
  post   'getdriverbooking'         => 'drivers#booking'  
  post   'updatedriverbooking'      => 'drivers#update_booking'
  post   'subvendorsignin'          => 'sub_vendors#signin#'
  post   'subvendorbookings'        => 'sub_vendors#bookings'
  post   'subvendorbooking'         => 'sub_vendors#booking'
  post   'subvendorupdatebooking'   => 'sub_vendors#update_booking'
  post   'subvendordrivers'         => 'sub_vendors#drivers'
  post   'subvendorassigndropdriver'=> 'sub_vendors#assign_drop_driver'    
  post   'subvendordriverbookings'  => 'sub_vendors#driver_bookings' 
  post   'subvendormakeoffer'       => 'sub_vendors#make_offer'
  post   'adminbookings'            => 'admins#bookings'
  post   'adminmanufacturers'       => 'admins#manufacturers'
  post   'adminusers'               => 'admins#users'
  post   'adminsignin'              => 'admins#signin'  
  post 'subvendorassignpickupdriver'=> 'sub_vendors#assign_pickup_driver'
  post   'admindealerships'         => 'admins#dealerships' 
  post   'adminbooking'             => 'admins#booking' 
  post   'admincreatevendor'        => 'admins#create_vendor'
  post   'adminuserdetails'         => 'admins#user_details' 
  post   'admingetvendors'          => 'admins#get_vendors' 
  post   'admingetsubvendors'       => 'admins#get_sub_vendors'                     
  post   'admingetdrivers'          => 'admins#get_drivers'
  post   'admincreatedealership'    => 'admins#create_dealership' 
  post   'admindriverdetails'       => 'admins#driver_details'
  post   'adminupdatebooking'       => 'admins#update_booking'  
  post   'admincreateoffer'         => 'admins#create_offer'  
  post   'adminremoveoffer'         => 'admins#remove_offer'            

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      post   'signup'                   => 'users#create'
      post   'uservehicles'             => 'users#user_vehicles'
      post   'userbookings'             => 'users#user_bookings'
      post   'tempotp'                  => 'users#send_otp'
      post   'resendtempotp'            => 'users#resend'
      post   'userupdate'               => 'users#update'
      post   'usernotifications'        => 'users#user_notifications'
      post   'resetpassword'            => 'password_resets#create'
      post   'updatepassword'           => 'password_resets#update'
      post   'verifyuser'               => 'otps#create'
      post   'resendotp'                => 'otps#update'
      post   'signin'                   => 'sessions#create'
      post   'vehicleupdate'            => 'vehicles#update'
      post   'removevehicle'            => 'vehicles#destroy' 
      post   'facebook'                 => 'sessions#facebook'
      post   'google'                   => 'sessions#google'
      post   'oauthmobile'              => 'sessions#oauth_mobile'
      post   'createvehicle'            => 'vehicles#create'
      post   'updatevehicle'            => 'vehicles#update'
      post   'createbooking'            => 'bookings#create' 
      post   'getdealers'               => 'vehicles#get_dealers_without_authentication'
      get    'allmanufacturers'         => 'manufacturers#index' 
      post   'allvehiclesofmake'        => 'manufacturers#all_vehicles'
      get    'allmodels'                => 'manufacturers#all_models'
      get    'manufacturerswithmodels'  => 'manufacturers#manufacturers_with_models'
      get    'alllocations'             => 'locations#index'
      get    'alloffers'                => 'offers#index'
      get    'alljobs'                  => 'jobs#index'
      post   'checkoffer'               => 'offers#check_offer'
      post   'createaddress'            => 'users#create_address'
      post   'alladdresses'             => 'users#user_addresses'
      post   'packages'                 => 'vehiclemodels#get_packages' 
      post   'jobs'                     => 'vehiclemodels#get_jobs'
      get    'washpackages'             => 'wash_bookings#get_wash_packages'
      post   'washbooking'              => 'wash_bookings#wash_booking'
      post   'allwashbookings'          => 'wash_bookings#wash_bookings'
      post   'userinfo'                 => 'users#get_user_info'
      post   'removeaddress'            => 'users#remove_address'
      post   'form'                     => 'sessions#form'
    end
  end

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :remember_digest %><br>
    <%= f.text_field :remember_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Image</th>
      <th>Remember digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.mobile %></td>
        <td><%= admin.email %></td>
        <td><%= admin.password_digest %></td>
        <td><%= admin.image %></td>
        <td><%= admin.remember_digest %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @admin.mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @admin.password_digest %>
</p>

<p>
  <strong>Image:</strong>
  <%= @admin.image %>
</p>

<p>
  <strong>Remember digest:</strong>
  <%= @admin.remember_digest %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>